In [2]:
import numpy as np

## Random Sampling with numpy.random.choice

The `np.random.choice` function in NumPy is used for random sampling from an array-like object or integer.

- `a`: The first argument can be either a 1-D array-like object, from which random samples are generated, or an integer. If it's an integer, the function behaves as if it's generating random samples from the range [0, a).

- `size` (optional): This argument specifies the size of the random sample to be generated. By default, if it's not provided (None), a single random value is returned. If provided, it determines the shape of the output, e.g., the number of samples to generate.

This function is commonly used for tasks such as random selection, permutation, or bootstrapping in data analysis and machine learning.

In [6]:
np.random.choice(5)

2

In [3]:
np.random.choice(5, 10)

array([1, 3, 2, 1, 0, 0, 3, 3, 0, 2])

In [7]:
np.random.choice([2, 4, 7, 9, 10, 89])

9

In [9]:
np.random.choice([2, 4, 7, 9, 10, 89], 3)

array([10, 89, 89])

## Setting Random Seed with np.random.seed()

In the context of random number generation, computers do not generate truly random numbers but use a deterministic algorithm that starts from an initial value known as a "seed." This process generates pseudorandom numbers.

The `np.random.seed()` function is used to set the seed for random number generation. By setting a seed, you make the random number generation predictable and reproducible. When the same seed is used, the sequence of random numbers generated will be the same.

This is valuable in scenarios where reproducibility is important, such as when running experiments, testing models, or debugging code. Setting a specific seed ensures that random operations are consistent across different runs.

It's important to note that changing the seed value will lead to a different sequence of random numbers, but using the same seed will result in the same sequence.

In [12]:
for _ in range(5):
  print(np.random.choice(10))

3
7
9
0
1


In [18]:
for _ in range(5):
  np.random.seed(0)
  print(np.random.choice(10))

5
5
5
5
5


## Generating Samples from the Standard Normal Distribution with np.random.randn()

The `np.random.randn()` function in NumPy is used to generate random samples from the "standard normal" distribution, which is also known as the standard Gaussian distribution.

- Syntax: `np.random.randn(d0, d1, ..., dn)`
  - `d0, d1, ..., dn`: The dimensions of the output. These are optional parameters and can be specified to determine the shape of the random sample. If not provided, a single random value is returned.

The standard normal distribution has a mean of 0 and a standard deviation of 1. Random samples generated using this function follow a bell-shaped curve, with most values clustered around 0 and tails extending to positive and negative infinity.

This function is frequently used in statistical analysis, simulations, and various applications in data science and machine learning.

In [20]:
np.random.randn()

1.040530750923964

In [21]:
np.random.randn(5)

array([-1.51698273, -0.86627621, -0.05503512, -0.10731045,  1.36546718])

In [22]:
np.random.randn(2, 3)

array([[-0.09769572, -2.42595457, -0.4530558 ],
       [-0.470771  ,  0.973016  , -1.27814912]])

## Generating Random Integers with np.random.randint()

The `np.random.randint()` function in NumPy is used to generate random integers within a specified range.

- Syntax: `np.random.randint(low, high, size)`
  - `low`: The lower bound of the range (inclusive). The generated random integers can be equal to this value.
  - `high`: The upper bound of the range (exclusive). The generated random integers will be less than this value.
  - `size` (optional): The size of the output. This determines the number of random integers to generate. It can be a single integer or a tuple specifying the shape of the output.

This function is commonly used for tasks such as random selection, shuffling, and generating random indices for sampling or permutation. It provides a convenient way to create random integers within a specified range.

In [23]:
np.random.randint(4, 9, 3)

array([4, 6, 7])

In [24]:
np.random.randint(4, 10, (2,2))

array([[4, 5],
       [7, 9]])

## Creating a Range of Values with np.arange()

The `numpy.arange()` function in NumPy is used to generate a sequence of values within a specified range.

- Syntax: `numpy.arange([start], stop, [step])`
  - `start` (optional): The starting value of the sequence. If not provided, the default value is 0.
  - `stop`: The end value of the sequence (exclusive).
  - `step` (optional): The step size between values in the sequence. If not provided, the default step size is 1.

The function generates values from `start` (or 0 if `start` is not provided) up to, but not including, `stop`, incrementing by `step` at each iteration.

This function is widely used for creating sequences of numbers, generating indices for iteration, or defining the range of values for various operations in numerical computing.





In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Concatenating Arrays with np.concatenate()

The `np.concatenate()` function in NumPy is used to join a sequence of arrays along an existing axis.

- Syntax: `np.concatenate((a1, a2, ...), axis=0)`
  - `a1, a2, ...`: Sequence of array-like objects that you want to concatenate.
  - `axis` (optional): The axis along which the arrays should be concatenated. Default is 0, meaning the first axis.

This function is commonly used when you need to combine multiple arrays into a single array, provided that:

- All input arrays have the same number of dimensions.
- The arrays have the same shape, except in the dimension corresponding to the specified `axis`.

The `np.concatenate()` function is flexible and allows for the combination of arrays in various ways, such as vertically (axis=0) or horizontally (axis=1), based on the specified axis.


In [32]:
a1 = np.array([4, 5, 7])
a2 = np.array([8, 1, 3])
np.concatenate((a1, a2), axis=0)

array([4, 5, 7, 8, 1, 3])

In [33]:
b1 = np.array([[1], [2], [3]])
b2 = np.array([[4], [5], [6]])
np.concatenate((b1, b2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Calculating Vector Norm with np.linalg.norm()

The `np.linalg.norm()` function in NumPy is used to calculate the norm (magnitude) of a vector.

- Syntax: `np.linalg.norm(x)`
  - `x`: The input vector or array for which you want to calculate the norm.

The function returns the norm of the input vector, which represents the length or magnitude of the vector. The norm can be calculated in different ways, including the L2 (Euclidean) norm, which is the default if not specified.

Calculating the norm of a vector is commonly used in various mathematical and numerical computations, including linear algebra, machine learning, and signal processing, to measure the size or distance of a vector from the origin (0,0) in a multi-dimensional space.


In [34]:
np.linalg.norm([1, 1])

1.4142135623730951

## Calculating the Distance between Two Vectors with `np.linalg.norm()`

The distance between two vectors, 'a' and 'b', can be determined by calculating the norm (magnitude) of the difference vector 'a - b' using the `np.linalg.norm()` function in NumPy.

- Syntax: `np.linalg.norm(a - b)`

This calculation measures the length of the vector 'a - b,' providing the distance between vectors 'a' and 'b' in the specified vector space.

The ability to compute the distance between vectors is valuable in a wide range of applications, including data analysis, machine learning, and geometry, where measuring the dissimilarity or similarity between data points or vectors is essential.

In [37]:
a1 = np.array([1, 3, 4])
a2 = np.array([3, 5, 6])

np.linalg.norm(a1-a2)

3.4641016151377544

## Finding the Index of the Minimum Value with np.argmin()

The `np.argmin()` function in NumPy is used to return the index (or indices) of the minimum values along a specified axis in an array.

- Syntax: `np.argmin(a, axis=None)`

- `a`: The input array in which you want to find the minimum value.
- `axis` (optional): The axis along which to search for the minimum value. Default is None, which means the array is flattened before searching.

The function returns the index (or indices) of the minimum value in the specified axis. If `axis` is not provided, the function searches for the minimum value across the entire array.

This function is valuable for tasks such as identifying the location of the minimum value within an array or selecting specific elements based on their minimum value.

In [38]:
a = np.array([3, 5, 6, 6, 9, 14])
np.argmin(a)

0

## Appending Values to an Array with `np.append()`

The `np.append()` function in NumPy is used to append values to the end of an array.

- Syntax: `np.append(array, values, axis=None)`

  - `array`: The input array to which you want to append values.
  - `values`: The values or array of values that you want to append.
  - `axis` (optional): The axis along which to append the values. If not specified, both the input array and values are flattened before use.

This function appends the specified values to the end of the given array and returns the resulting array. It's important to note that `np.append()` only creates a view of the array and does not modify the original array.

It is commonly used for extending arrays by adding new elements or data points at the end.

In [39]:
x = np.array([3, 6, 8, 10, 13])
np.append(x, 10)

array([ 3,  6,  8, 10, 13, 10])

In [40]:
np.append(x, [6, 9])

array([ 3,  6,  8, 10, 13,  6,  9])

## Calculating the Mean of an Array with `np.mean()`

The `np.mean()` function in NumPy is used to compute the arithmetic mean (average) of the elements in an array along a specified axis.

- Syntax: `np.mean(array, axis=None)`

  - `array`: The input array for which you want to calculate the mean.
  - `axis` (optional): The axis along which to compute the mean. Default is None, which means the array is flattened before finding the mean.

The function returns the mean of the array's elements. When the `axis` parameter is not specified, the mean is calculated by flattening the entire array.

This function is commonly used for calculating the average value of data in numerical computations, statistics, and various data analysis tasks.

In [41]:
a = np.array([4, 7, 8])
np.mean(a)

6.333333333333333

## Broadcasting in NumPy

Broadcasting is a feature in NumPy that allows arrays with different shapes to be combined in a way that makes sense for element-wise operations. This functionality is particularly useful when working with arrays of different shapes or sizes.

The key points to understand about broadcasting in NumPy are:

- When performing element-wise operations between arrays, NumPy compares their shapes element by element, starting from the trailing dimensions and working backward.
- Two dimensions are compatible when they are equal or one of them is 1.
- Broadcasting allows operations on arrays with different shapes to be performed without the need for manual resizing or duplicating data.

Overall, broadcasting simplifies element-wise operations between arrays of varying shapes, making it easier to work with and combine data efficiently in numerical computations and data analysis.


In [42]:
a1 = np.array([[1, 2], [4, 6]])
a1

array([[1, 2],
       [4, 6]])

In [43]:
a1 + [1, 1]

array([[2, 3],
       [5, 7]])

## Accessing array elements

In [46]:
x = np.array([1, 4, 5, 7, 8, 10, 95, 55])
x[[1, 3, 7]]

array([ 4,  7, 55])

In [47]:
x[[True, False, True, False, False, True, True, False]]

array([ 1,  5, 10, 95])